# Theme
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default"

# Site Settings
locale: "en-US"
title: "Computational Nano-Bio Chemistry Lab."
title_separator: "-"
name: "CNBC"
description: "Department of Chemistry, Seoul National University"
url: "snucnbc.github.io"
baseurl: ""
