# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Home
    link: /
  - name: About Us
    link: /
  - name: People
    submenu:
      - name: Prof. YounJoon Jung
        link: /people/prof
      - name: Group Members
        link: /people/gm
      - name: Past Members
        link: /people/pm
  - name: Publications
    link: /
  - name: Photo Gallery
    link: /about
    
